# Site settings
title: Ryan P. Garrett
email: ryan.p.garrett@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my new blog page. I just started using jekyll so this blog is naturally built with jekyll. Conveniently Github works well with jekyll so, why not :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ryanpgarrett.github.io" # the base hostname & protocol for your site
twitter_username: ryanpgarrett
github_username:  ryanpgarrett

# Build settings
markdown: kramdown
